/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"
import { expect } from "chai"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("profileGet", () => {
    const id: string = "id_example"
    return expect(instance.profileGet(id, {})).to.be(null)
  })
  test("secureAuthGet", () => {
    return expect(instance.secureAuthGet({})).to.be(null)
  })
  test("secureCallbackGet", () => {
    const oauth: api.DorrHttpOAuth = undefined
    const state: string = "state_example"
    return expect(instance.secureCallbackGet(oauth, state, {})).to.be(null)
  })
  test("statusGet", () => {
    return expect(instance.statusGet({})).to.be(null)
  })
  test("uploadPost", () => {
    const body: Object = undefined
    return expect(instance.uploadPost(body, {})).to.be(null)
  })
})

